### ISSUE TITLE
Hidden files

### ISSUE THREAD

**Issue by ghost** [jonhoo/proximity-sort#6]

**Comment by jonhoo** [comment]
Hmm, that's interesting. Do those same files show up if you don't include `proximity-sort` in the pipeline? `proximity-sort` really doesn't do anything fancy, and shouldn't add or remove files from the listing, just re-order them.

**Comment by facadeproof** [comment]
Well if I don't include the pipeline my config crashes, but it's not that some files are missing, it's that the order of the files seems a bit random. 

For example I'm editing my `~/.config/nvim/init.vim` and the files at the top of the `fzf` results are `~/.config/nvim/coc-settings.json` and `~/.config/nvim/ultisnips/markdown.snippets` but then a `xsel.log` or a `gtkrc-2.0` from my `$HOME` directory will show up, with other files from my `~/.config` folder above.

**Comment by jonhoo** [comment]
Huh, that is very weird indeed. Can you give me a specific input that produces weird ordering? I want to see what happens if we pass _just_ that file list through `proximity-sort`.

**Comment by facadeproof** [comment]
![screencast](https://0x0.st/iViO.gif)

In this screencast I'm on my `~/dotfiles/nvim/.config/nvim/init.vim` and I input `zsh` trying to get the results from my `~/dotfiles/zsh/` folder at the top. However, notice that I get results mixed up with files in my `~/.cache` and `~/void-packages` directories.

**Comment by jonhoo** [comment]
It'd be really useful to see exactly what output the underlying find command yields, and what argument is provided to `proximity-sort`. It's hard to debug just from that screencast, even though it does demonstrate the problem.

**Comment by jonhoo** [comment]
@facadeproof Did you find a solution to your problem? It'd be great if you could share the solution instead of deleting the question :)

**Comment by facadeproof** [comment]
Sorry, I kind of gave up after multiple attempts. I also tried to adapt the provided shell script on my `.zshrc` and set up the following 
```sh
function fzf-proximity {
  local file
  file="$(fd -t f --follow --hidden . $HOME | proximity-sort $PWD | fzf --tiebreak=index)"

  if [[ -n $file ]]; then
    nvim -- $file
    # fix cursor turning into normal mode
    echo -ne '\e[5 q'
  fi
}

zle -N fzf-proximity

bindkey "^F" fzf-proximity
```

to try to reproduce the behaviour on vim, and the weird sorting occurs too.

**Comment by jonhoo** [comment]
Interesting.. It'd still be very useful if you could provide the input to `proximity-sort`, and the argument you pass to it. That way it'd be much easier for me to replicate your problem.

**Comment by facadeproof** [comment]
Ok, so if I'm understanding you correctly, this is what I have as my `list_cmd` function on my `~/.config/nvim/init.vim`

```viml
function! s:list_cmd()
  let base = fnamemodify(expand('%'), ':h:.:S')
  return base == '.' ? 'fd -t f --follow --hidden' : printf('fd -t f --follow --hidden | proximity-sort %s', expand('%'))
endfunction

command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, { 'source': s:list_cmd(),
  \                               'options': '--tiebreak=index' }, <bang>0)

nnoremap <silent><c-f> :Files<CR>
```
It basically is the same as the one provided on the `README` with tweaks to the `fd` command. 

To replicate, I'm in my home directory and I go my `~/.config/nvim/init.vim` through the hotkey `ctrl+f` defined in my previously mentioned `.zshrc`, then I call the the fzf `Files` command with `ctrl+f`, and I look for `zsh`. 

The first result is a file `.zshenv` in my home directory, the next one is `~/dotfiles/zsh/.zshenv` (this one makes sense because I have the `--follow` flag enabled, although I'm not sure it should be sorted like this), and then the rest of the results are a mix of files in my `~/.cache`, `~/void-packages`, `~/dotfiles` and `~/.config` directories. 

Now, what ideally should happen is that the results belonging to my `~/dotfiles` and `.config` folder show up first as they are the ones closer to the directory I'm currently in (as `.config` is almost made up of symlinks to `dotfiles`), but instead I'm presented with an usual sorting.

**Comment by jonhoo** [comment]
Ah, sorry, no, when I say "input" I mean the actual list of files produced by the command to the left of `| proximity-sort` that's causing you problems. This should just be a matter of running the same command you have in your config manually, without `| proximity-sort`, in the same directory. And then also what argument is passed to `proximity-sort` when you see the problematic behavior (what's provided as `%s` above).
